name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  # Optional: trigger on new tags
  # tags:
  #   - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: donuva2
        password: dckr_pat_hNUkzElUQGYRk2bARsmIUsdYK54

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile # or ./Dockerfile
        push: true
        tags: donuva2/simu_5g
